### ISSUE TITLE
Hai bisogno di correggere le icone! 

### ISSUE THREAD

**Issue by gusbemacbe** [Bonandry/suru-plus-ubuntu#55]
Ciao @Bonandry!

Io ti ho inviato le immagini sul Hangouts, ma non hai letto. Eccole: 

L'icona è grande troppo. 

![grande icona](https://i.imgur.com/0CZfv1l.png)
 
Le lettere sono illeggibili da vedere. Le icone hanno differenti colori. L'icona della prima immagine è grigia e la seconda è azzurra grigiastra. Comparale:

Azzurra grigiastra
![lettere illegibili](https://i.imgur.com/yibQjsa.png) 

Grigia
![differente colore](https://i.imgur.com/cZ4b1bp.png)

**Comment by gusbemacbe** [comment]
Scusami, io ho dimenticato di altra immagine! Io ho aggiornato il suggerimento.

**Comment by Bonandry** [comment]
ciao Gus, penso di aver corretto

**Comment by gusbemacbe** [comment]
L'icona https://github.com/Bonandry/suru-plus/blob/a6c44dfdbd2248511a89dd56e99eaf34253498c2/apps/16/com.github.bilelmoussaoui.Authenticator.svg è molto grande.

**Comment by Bonandry** [comment]
grazie, risolto

**Comment by Bonandry** [comment]
Gus, il set dovrebbe essere completo anche per 19.04

**Comment by gusbemacbe** [comment]
> Gus, il set dovrebbe essere completo anche per 19.04

Significhi GNOME 3.32? 

Le ho aggiunte oggi. 

Sono le icone `org.gnome.[lettera--iniziale-maiuscola]*`

**Comment by gusbemacbe** [comment]
Puoi prendere le icone del GNOME 3.32  dal mio commit: 

https://github.com/gusbemacbe/suru-plus/commit/9a87eb75e8fbc280b0923b8c4e0078dcbe398533

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

Abbiamo bisogno di cambiare l'indirizzo del repositorio di `/Bonandry/suru-plus` per `/Bonandry/suru-plus-ubuntu`. Anche ho bisogno aggiornare il tuo prodotto sull'OpenDesktop.

**Comment by Bonandry** [comment]
certo, procedi pure

**Comment by gusbemacbe** [comment]
@Bonandry 

Io ho aggiornato il tuo repositorio sul GitHub e il prodotto sull'OpenDesktop.

Ti piacerebbe ch'io entrassi con il tuo account nel forum di OpenDesktop per chiedere agli amministratori di OpenDesktop per cambiare il tuo cognome di Magog64 per Bonandry?

**Comment by Bonandry** [comment]
Certo, potresti anche aggiungere che il set è aggiornato per la 19.04?

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

Stai certo. Io ho dimenticato, io vado aggiornarli.

**Comment by gusbemacbe** [comment]
@Bonandry 

Pronto!

Penso che tu devi migliore l'immagine del tuo profilo:

![imagem](https://user-images.githubusercontent.com/2257024/54661035-75f56d80-4ab7-11e9-8f23-e848fde7abc8.png)

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

Pronto, io ho inviato la sollecitazione agli amministratori dell'OpenDesktop per modificare il tuo cognome. Aspettiamo loro risposta.

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

Io ho fatto un _upgrade_ del tuo tema di icone, perché gli utente vogliono aggiornare rapidamente senza andare tutta volta al GitHub. Vedi il https://github.com/Bonandry/suru-plus-ubuntu/tree/beta.

Ti piace? Se sì, io vado fare _merg_ la versione `beta` nella versione `master`. 

Mi piacerebbe mostrarti un nuovo logo:

<img width="256" alt="new-logo" src="https://user-images.githubusercontent.com/2257024/54665211-23bb4900-4ac5-11e9-932f-8c8369f4bbe2.png">

Se non ti piace, ti raccomando a fare un nuovo logo con un nuovo nome.

**Comment by Bonandry** [comment]
Molto bene grazie

**Comment by gusbemacbe** [comment]
@Bonandry, pronto, io ho transferito la branch/versione "master" per la versione "vecchio", e "beta" per "master".

Io vado aggiornare il tuo prodotto sull'OpenDesktop.

**Comment by gusbemacbe** [comment]
Pronto. Tutto finito e aggiornato.

**Comment by gusbemacbe** [comment]
@Bonandry , Travis mi ha avvertito che ci sono molti errori sulla cartella `symbolic` della cartella `apps`. Ho visto che hai messo le icone non-simbolici là. Devi stare attento, ma io vado fissarli.

Non fare niente, per favore, perché io sto fissandoli.

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

Io ho fissato tutti gli errori. Non solo che hai messo le icone non-simboliche nella cartella di icone simboliche, anche hai messo le icone simbolici nella cartella di icone non-simboliche. Devi star sempre attento. 

Anch'io fissato poche icone di `actions` che hai rimosse:

* Suru++-Ubuntu/actions/22/document-save-all.svg: hai rimosso, causando la rottura di alcune icone
* Suru++-Ubuntu/actions/22/document-save.svg: hai rimosso, causando la rottura di alcune icone
* Suru++-Ubuntu/actions/22/edit-delete.svg: hai rimosso, causando la rottura di alcune icone
* Suru++-Ubuntu/actions/22/system-suspend.svg: l'hai rimossa, ho copiato dal mio Suru++ 25, devi rifarla allo stilo di Suru++ Ubuntu. 
* Suru++-Ubuntu/actions/22/system-switch-user.svg:  l'hai rimossa, ho copiato dal mio Suru++ 25, devi rifarla allo stilo di Suru++ Ubuntu. 

E ho fissato poche icone rotte di `mimetypes`, perche le hai rimosse:

* Suru++-Ubuntu/mimetypes/16/application-pgp-keys.svg
* Suru++-Ubuntu/mimetypes/16/encrypted-key.svg
* Suru++-Ubuntu/mimetypes/16/shellscript.svg

Finalmente, ho utilizzato il mio `ffsvg` per ottimizzare la dimensione del tuo tema. 

Io ho rimosso tutte le icone simbolichi di `apps/16` e tutte le icone non-simbolichi di `apps/symbolic`.

**Comment by gusbemacbe** [comment]
Ciao @Bonandry 

IO ho aggiornato, la descrizione sta in italiano: https://github.com/Bonandry/suru-plus-ubuntu/commit/c110e311004b4f2a7f7e157f32b0e65ea9a9c53c (fa un clic)

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

Ci eranno ancore pochi errori, perché alcune icone di cui tu hai incorporato le immagini – abiword, draftsight e mypaint. Io le ho già mgliorato. 

Finalmente, Travis CI ha finito di dire che c'è nessuno errore nel tuo tema di icone.

**Comment by gusbemacbe** [comment]
E per favore non rimovere i file:

* .gitattributes
* .gitignore
* .travis.yml
* install.sh
* Makefile

Perché sono importanti per il Travis CI verificare se ci sono o non errori nel tuo tema di icone.

Per favore non mettere niente sulla versione `master` perché `master` è para il rilascio ufficiale. Invece,  mettile sulla versione `beta` per il teste e le build notturne.  

Rimovere il tuo repositorio del tuo computer e esegui il commando sul terminale:

```
git clone -b beta --single-branch https://github.com/Bonandry/suru-plus-ubuntu
```

Adesso puoi metterle sulla versione `beta` clonata.

**Comment by Bonandry** [comment]
grazieeeeeeee

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

* Io ho corretto i colori erronei di icone di `apps/16`, per esempio, `#666666` per `#808080`;
* Io ho rimosso le icone simboliche di `categories/16`;
* Io ho ottimizzato le icone di `categories/16`;
* Io ho corretto i colori erronei di `apps/symbolic` e fatto la sua ottimizzazione;
* Io ho ottimizzato la `categories/symbolic`;
* Io ho corretto i colori erronei di `categories/16` e `categories/symbolic` ed ottimizzato la `categories/scalable`;

Molto similare al mio Suru++ 25 e al Papirus di @SmartFinn, io ho unificato le cartelle `apps` e `categories` solamente in una cartella per **facilitare e velocizzare il tuo lavoro**.

**Comment by Bonandry** [comment]
ottimo, ho corretto due icone "libreoffice-calc e sopcast-player"

**Comment by gusbemacbe** [comment]
Ciao @Bonandry , io ho fatto `git pull` di queste due icone`. Adesso, io sto ottimizzando la cartella `mimetypes` e correggendo i colori erronei.

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

Ottimizzazione e corezzione dei colori erronei:

* Ottimizzate le cartelle `devices`, `emblems`, `emotes`, `mimetypes`, `places` e `status`;
* Corretti i colori erroni di icone di `devices/16`, `emblems/16`, `emotes/16`, `mimetypes/16`, `places/16`.
* Corretti i colori erroni di icone di `devices/symbolic`, `emblems/symbolic`, `emotes/symbolic`, `mimetypes/symbolic`, `places/symbolic`.

Con l'ottimizzazione del tema **intero**, 53,8% della sua dimensione è ridotta (dal 78MB per 42MB)! 

Io credo che dobbiamo rimuovere la cartelle `actions` e copiare nuovamente la cartella `actions` del tema di icone Yaru, perché la la maggior parte delle icone di `actions` sono icone di Breeze, che è de KDE.

**Comment by gusbemacbe** [comment]
Ti piacerebbe ch'io rimossi la cartella `actions` e copiassi la cartella `actions` del Yaru?

**Comment by Bonandry** [comment]
mi sembra che Yaru non ha le action

**Comment by Bonandry** [comment]
comunque prova e vediamo come funziona

**Comment by Bonandry** [comment]
ci sono dei colori errati anche nella cartella status 16, io li ho risolti se vuoi li carico, la cartella 32 non è indispensabile

**Comment by gusbemacbe** [comment]
@Bonandry 

> mi sembra che Yaru non ha le action
Stano in `suru-icon-theme/Suru/scalable/actions/`, ma sono simboliche. Io so come sostituirle per quelle non-simbolici

> ci sono dei colori errati anche nella cartella status 16, io li ho risolti se vuoi li carico, la cartella 32 non è indispensabile

Per favore!

**Comment by gusbemacbe** [comment]
Eccole per scaricare:

[actions.tar.gz](https://github.com/Bonandry/suru-plus-ubuntu/files/2991940/actions.tar.gz)

**Comment by Bonandry** [comment]
si ma mancano tutte quelle per inkscape, evolution e altri programmi

**Comment by Bonandry** [comment]
ho fatto la cartella STATUS

**Comment by gusbemacbe** [comment]
@Bonandry 

Copia solamente le icone di Inkscape, Evolution e d'altri programmi. Non copia tutto, perché molte icone sono di KDE e tu non le vorrai sul tuo tema di icone esclusivamente per Ubuntu e GNOME. 

Se credi che ciò prende molto tempo per copiare, tu puoi scaricare un piccolo pacchetto di icone di Inkscape e modificarle rapidamente e facilmente allo stilo di Suru:

* Inkscape: https://www.opendesktop.org/p/1168331/ (colorito) e https://www.opendesktop.org/p/1168718/ (monocromatico)
* Evolution: https://www.opendesktop.org/p/1012482/

**Comment by gusbemacbe** [comment]
Ecco le icone di Evolution. Tu trovi le icone con ognuno categoria `actions`, `status`, ecc., con ognuna dimensione:

https://gitlab.gnome.org/GNOME/evolution/tree/master/data/icons

**Comment by gusbemacbe** [comment]
E le icone di GIMP per scaricare: [gimp-icons.tar.gz](https://github.com/Bonandry/suru-plus-ubuntu/files/2993946/gimp-icons.tar.gz)

Se vuoi le icone in SVG, loro stano nelle cartelle `scalable` delle cartelle Color e in Symbolic. Crea solamente le cartelle `16`, `scalable` e `symbolic`

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

Io ho migliorato l'icona. 

* Prima:

![web-browser-before](https://user-images.githubusercontent.com/2257024/54819590-21025480-4c7b-11e9-8dd8-aed70065266f.png)

* Dopo:

![web-browser-after](https://user-images.githubusercontent.com/2257024/54819601-2a8bbc80-4c7b-11e9-80f4-d4e1a5c89b6c.png)

**Comment by gusbemacbe** [comment]
Anch'io ho migliorato l'icona di macchina calcolatrice:

* Prima:

![calculator-before](https://user-images.githubusercontent.com/2257024/54820338-95d68e00-4c7d-11e9-804f-30840b36c05a.png)

* Dopo:

![calculator-after](https://user-images.githubusercontent.com/2257024/54820347-9ec75f80-4c7d-11e9-96f5-74e44d1039cd.png)

**Comment by gusbemacbe** [comment]
* Prima:

![imagem](https://user-images.githubusercontent.com/2257024/54820875-5446e280-4c7f-11e9-8572-159ce4c600c7.png)

* Dopo:

![imagem](https://user-images.githubusercontent.com/2257024/54820935-7e000980-4c7f-11e9-9412-842d2078174c.png)

**Comment by gusbemacbe** [comment]
@Bonandry, io ho bisogno di esplicarti.

Le icone di dizionario, di libro/libro elettronico e di visualizzatore di documento PDF non devono essere le stesse cose perché gli utente si sentiranno confusi. 

* Le icone di dizionario devono essere un'icona di dizionario.
* Le icone di libro o libro elettronico devono essere un'icona di libro.
* Le icone di visualizzatore di documento PDF devono essere un'icona di visualizzatore di documento.

1. Fammi tre icone colorite differente, una di dizionario, una di documento PDF e una di libro. E altre tre icone monocromatiche.
2. Nominale come "dizonario.svg", "libro.svg" e "visualizzatore.svg" ch'io vado metterle sulla cartella `icone-generiche`, per **facilitare e velocizzare** il tuo lavoro senza dovere continuare a cercare abbastanza. 
3. Comprimile come `.tar.gz` e **puoi mettere l'archivio compresso qui**.

**Comment by gusbemacbe** [comment]
Ah, OpenDesktop ti ha risposto riguardo il tuo nome di utente. Loro hanno detto che cambiare il nome di utente è un processo abbastanza complicato, perché qualsiasi nome di utente è connesso a tutti i servizi opendesktop.org, come Discourse, Gitlab e Riot. Ma loro hanno iniziato a cercare un modo, ma finché che loro abbiano completato con il loro scambio openID universale, ciò potrebbe non essere fattibile per il momento.

![imagem](https://user-images.githubusercontent.com/2257024/54823396-7a23b580-4c86-11e9-8374-55745d518bce.png)

**Comment by Bonandry** [comment]
modificare tutte le icone per Evalution e Inkscape mi porta via molto tempo e ora non posso
le tre icone te le ho inviate su hangout

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

> modificare tutte le icone per Evalution e Inkscape mi porta via molto tempo e ora non posso

OK, posso presumere il tuo posto per lavorare con ciò, so dove sono le icone que hai disegnato per Evolution ed Inkscape.

**Comment by Bonandry** [comment]
ho eliminato una parte delle icone per kde, manca da colorate in 808080ff

**Comment by gusbemacbe** [comment]
> manca da colorate in 808080ff

Puoi utilizzare il mio `ffsvg` per ottimizzare e pulire i codici sporchi di Inkscape, dopo sostituirai per 808080 invece di 808080ff, rapidamente una volta per tutte, utilizzando il commando `sed`:

```
cd Suru++-Ubuntu/actions/16
sed --in-place --follow-symlinks 's/#colorito_erroneo/#808080/g' *.svg
```

**Comment by Bonandry** [comment]
non so come fare

**Comment by gusbemacbe** [comment]
Io posso fare ciò. 

Quali i colori erronei hai trovato nelle icone di actions?

**Comment by Bonandry** [comment]
non so come fare

**Comment by Bonandry** [comment]
ho eliminato altre icone e ho fatto i collegamenti 24 e 32 ma non riesco a caricare il file mi da questo errore "action-albumfolder-importdir2.svg"

**Comment by Bonandry** [comment]
ho messo nelle ICONE GENERICHE le ACTION 16 dove c'è una icona che da dei problemi, devono essere colorate in 808080ff e i collegamenti 24 e 32

**Comment by gusbemacbe** [comment]
Io vado testarli.

**Comment by gusbemacbe** [comment]
Io ho appena fatto. Senza errore. Ma hai fatto il collegamento di actions/16 alle cartelle actions/22, actions/24 e actions/32, certo?

**Comment by gusbemacbe** [comment]
AH, Travis CI mi ha detto che c'è un errore di una icone collegata che dipende dell'icona originale che hai rimossa:

`./Suru++-Ubuntu/actions/16/template.svg -> document-new-from-template.svg`

`template.svg` è un'icona di GNOME e d'Ubuntu?

**Comment by Bonandry** [comment]
no è da eliminare

**Comment by Bonandry** [comment]
![Schermata da 2019-03-23 09-19-09](https://user-images.githubusercontent.com/7957697/54863746-c5080080-4d4c-11e9-8b4b-462abd54b2c6.png)
IL PROBLEMA RIMANE ANCHE DOPO AVERE ELIMINATO L'ICONE TEMPLATE

**Comment by gusbemacbe** [comment]
@Bonandry 

Hai TeamViewer per io correggere l'errore?

Apri il terminale:

```
cd suru-plus-ubuntu
git difftool
```
Prendi il sul screenshot ed inviamelo per vederlo.

**Comment by gusbemacbe** [comment]
Io ho eliminato l'icona di `action-albumfolder-importdir2.svg`. ESegui il commando sul terminale:

```
cd suru-plus-ubunu
git pull
```

**Comment by gusbemacbe** [comment]
Travis CI mi ha detto che c'è nessuno errore adesso. Fa il `git pull`.

**Comment by gusbemacbe** [comment]
I0 ho spostato le due icone sulla nuova cartella `backup` se hai bisogno di loro.

**Comment by Bonandry** [comment]
è possibile colorare tutte le piccole icone in 4d4d4dff ?

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !


Si, è possibile, ecco i commandi:

```
cd Suru++-Ubuntu/actions/16
sed --in-place --follow-symlinks 's/#colori_vecchio/#colori_nuovo/g' *.svg
```

Significa:

```
sed --in-place --follow-symlinks 's/#4d4d4dff/#808080ff/g' *.svg
```

**Comment by Bonandry** [comment]
problema 1, ho ancora il problema, 
ho eliminato la cartella con l'errore e ho scaricato quelle corrette,
ho caricato su GITHUB il set e ho apportato le modifiche (come in foto)
mi da sempre lo stesso errore
![Schermata da 2019-03-23 09-51-45](https://user-images.githubusercontent.com/7957697/54864077-ce479c00-4d51-11e9-8a30-5689162d7792.png)

**Comment by Bonandry** [comment]
problema 2 cambio colore
![Schermata da 2019-03-23 09-53-14](https://user-images.githubusercontent.com/7957697/54864080-def81200-4d51-11e9-82b3-2a4323fa8170.png)

**Comment by gusbemacbe** [comment]
Hai TeamViewer, @Bonandry, per io corrigerli?

**Comment by Bonandry** [comment]
no, ho messo nella cartella ICONE un archivio con le action giuste

**Comment by gusbemacbe** [comment]
Io ho aggiornato. Io sto aspettando l'analisi di Travis CI.

**Comment by Bonandry** [comment]
ok

**Comment by gusbemacbe** [comment]
Nessun errore. Elimina il tema di icone, apri il terminale, carica nuovamente il tema di icone col commando seguente:

```
git clone -b beta --single-branch https://github.com/Bonandry/suru-plus-ubuntu ~/suru-plus-ubuntu
ln -sfnr ~/suru-plus-ubuntu/Suru++-Ubuntu ~/.icons/Suru++Ubuntu
```

**Comment by Bonandry** [comment]
ok funziona, ho portato le action a 1954
ora devo solo colorarle a 4d4d4dff
provo con il comando che mi hai dato

**Comment by Bonandry** [comment]
ho provato, non ho errori ma il colore non è cambiato

**Comment by gusbemacbe** [comment]
Io ho visto le icone, loro utilizzano `#4d4d4d` e non `#4d4d4dff`. Ecco il commando:

```
sed --in-place --follow-symlinks 's/#4d4d4d/#808080/g' *.svg
```

**Comment by Bonandry** [comment]
molte le ho cambiate ma molte altre, le Yaru, non si colorano rimangono 808080
![Schermata da 2019-03-23 11-04-32](https://user-images.githubusercontent.com/7957697/54864728-9b0a0a80-4d5b-11e9-8f26-fc75360f8c70.png)

**Comment by gusbemacbe** [comment]
Alcune icone utilizzano `#808080`, altre utilizzano `#808080ff`.

Il `#808080ff` è un codice esadecimale di linguaggio di programmazione di Inkscape. I linguaggi di SVG e di Inkscape sono differenti.

Per correggere, ottimizzare per i codici puri in SVG, per favore utilizza il mio `ffsvg`:

```
sudo apt install subversion
svn export https://github.com/gusbemacbe/suru-plus.git/trunk/scripts ~/scripts
gedit ~/.bashrc
```

Il file `.bashrc` sarà aperto con Gedit e metti:

```
alias ffsvg='/home/andrea/scripts/ffsvg.sh'
```

Sul terminale, esegui:

```
source ~/.bashrc
cd ~/.icons/Suru++Ubuntu/actions/16
ffsvg ./
```
I codici esadecimali saranno ottimizzati (#808080ff per #808080) ed i codici di Inkscape saranno purificati nel linguaggio di SVG. Dopo, puoi provare il commando di sostituire i colori.

**Comment by Bonandry** [comment]
alias ffsvg='/home/andrea/scripts/ffsvg.sh'
DOVE LO DEVO METTERE?

**Comment by gusbemacbe** [comment]
Nel file `.bashrc`.

Apri il Nautilus, stampa Ctrl + H, e vai alla cartella del tuo nome, e vederai il file ".bashrc".

**Comment by Bonandry** [comment]
la stringa dove la devo copiare, 
alla fine o all'inizio dello script

**Comment by gusbemacbe** [comment]
Alla fine.

**Comment by Bonandry** [comment]
ok sta lavorando

**Comment by gusbemacbe** [comment]
Ha funzionato?

**Comment by Bonandry** [comment]
fatto ma alcune icone non cambiano colore neanche dopo lo script

**Comment by gusbemacbe** [comment]
Può essere che loro utilizzano altri colori.

**Comment by gusbemacbe** [comment]
Io sto lavorando con ciò. OK?

**Comment by gusbemacbe** [comment]
Tu vuoi que tutte le icone di `actions/16` siano `#4f4f4f`?

**Comment by gusbemacbe** [comment]
Le icone di `actions/16` stano pronte e aggiornate. Io vado lavorare con `actions/symbolic`.

**Comment by gusbemacbe** [comment]
Io ho finito la cartella `actions/symbolic`.

**Comment by Bonandry** [comment]
Ok, ora sono al lavoro

**Comment by Bonandry** [comment]
ottimo

**Comment by gusbemacbe** [comment]
Hai visto l'icona di "dizionario.svg" sulla cartella "icone-generiche"? Cosa ne pensi?

**Comment by gusbemacbe** [comment]
Io ho migliorato l'icona.

![rubrica](https://user-images.githubusercontent.com/2257024/54879662-49748500-4e1a-11e9-9af0-52a51c2c7591.png)

**Comment by gusbemacbe** [comment]
L'icona di tabella di caratteri

![tabella-caratteri](https://user-images.githubusercontent.com/2257024/54879957-3cf22b80-4e1e-11e9-95bb-19ed52dde05e.png)

**Comment by gusbemacbe** [comment]
@Bonandry 

Ecco l'icona migliorata di Amazon. Io ho aggiungo le icone perdute di Android Studio.

![amazon](https://user-images.githubusercontent.com/2257024/54880235-6791b380-4e21-11e9-96e4-ede86ccd6783.png)

**Comment by gusbemacbe** [comment]
Migliorata l'icona di Ardour:

![ardour](https://user-images.githubusercontent.com/2257024/54880493-d839cf80-4e23-11e9-8f0a-44c0e94afe75.png)

**Comment by gusbemacbe** [comment]
Io ho migliorato l'icona d'Artha:

![artha](https://user-images.githubusercontent.com/2257024/54880626-4af77a80-4e25-11e9-9d0e-448dde47483a.png)

**Comment by gusbemacbe** [comment]
D'Ask Ubuntu:

![askubuntu](https://user-images.githubusercontent.com/2257024/54880768-8a26cb00-4e27-11e9-8a06-43779c792a24.png)

**Comment by Bonandry** [comment]
> Hai visto l'icona di "dizionario.svg" sulla cartella "icone-generiche"? Cosa ne pensi?

mi sembra troppo elaborata, ti ho messo la mia versione

**Comment by gusbemacbe** [comment]
Perfetto, io scelgo la tua.

**Comment by gusbemacbe** [comment]
Qual una delle è corretta?

![imagem](https://user-images.githubusercontent.com/2257024/54881405-5ac78c80-4e2e-11e9-8101-64352c97a6a2.png)

**Comment by Bonandry** [comment]
> Qual una delle è corretta?
> 
> ![imagem](https://user-images.githubusercontent.com/2257024/54881405-5ac78c80-4e2e-11e9-8101-64352c97a6a2.png)

la 2 e la 3

**Comment by Bonandry** [comment]
nelle icone generiche ho messo
calculator con i colori di gnome 3.32
askubuntu con il contorno perché era mancante

**Comment by gusbemacbe** [comment]
> calculator con i colori di gnome 3.32
askubuntu con il contorno perché era mancante

Io vado sostituire.

**Comment by gusbemacbe** [comment]
Ciao @Bonandry 

![imagem](https://user-images.githubusercontent.com/2257024/54881839-096dcc00-4e33-11e9-8931-88d0b2a00943.png)

Atom e Atomic sono differenti. Atom è un edittore di testo, ma Atomic è un gioco. Ecco la mia icona per vedere:

https://github.com/gusbemacbe/suru-plus/blob/master/Suru++/apps/64/katomic.svg

**Comment by gusbemacbe** [comment]
Io ho migliorato l'icona di Tor Browser

![tor](https://user-images.githubusercontent.com/2257024/54882223-7c2c7680-4e36-11e9-89cb-581dc2f17c28.png)

**Comment by Bonandry** [comment]
ho messo 2 prove, la seconda l'avevo fatta colorata ma mi risulta grigia...?

**Comment by Bonandry** [comment]
ho messo anche una versione c

**Comment by gusbemacbe** [comment]
L'icona `c.svg` é migliore perché é molto legibile di altre due versione.

**Comment by Bonandry** [comment]
ok

**Comment by gusbemacbe** [comment]
IO ho aggiornato le icone migliorate da te.

Anche ho migliorato l'icona di DevHelp:

![devhelp](https://user-images.githubusercontent.com/2257024/54883697-257b6880-4e47-11e9-997b-5f03318d7a30.png)

**Comment by gusbemacbe** [comment]
Ho migliorato l'icona di driconf:

![driconf](https://user-images.githubusercontent.com/2257024/54883853-fe259b00-4e48-11e9-879d-9efa15cb4b7f.png)

**Comment by Bonandry** [comment]
Gus una domanda, io non le vedo tutte queste icone errate

**Comment by gusbemacbe** [comment]
Utilizzo il Dolphin File ed Plank sul GNOME. Loro sembrano buone sul Nautilus, ma non sul Dolphin e sul Plank.

Fa un clic sull'immagini per visualizzare.

![esempi](https://user-images.githubusercontent.com/2257024/54884297-e7357780-4e4d-11e9-9cf0-11183a62c726.png)

**Comment by gusbemacbe** [comment]
Perciò, io le ho tutto corrette e migliorate.

**Comment by Bonandry** [comment]
ecco perché io non vedevo errori (y)

**Comment by gusbemacbe** [comment]
Ho appena aggiornato e migliorato l'icona `electrum-ltc.svg`:

![electrum-ltc](https://user-images.githubusercontent.com/2257024/54884792-beb07c00-4e53-11e9-83bf-88e5134a3314.png)

**Comment by Bonandry** [comment]
quella che avevo io è di un altro colore

**Comment by Bonandry** [comment]
in GENERICHE ho messo la base per le icone

**Comment by gusbemacbe** [comment]
@Bonandry , quale il colore originale? Grazie per la template!

**Comment by Bonandry** [comment]
il colore è giusto il tuo io lo avevo celeste molto chiaro

**Comment by gusbemacbe** [comment]
L'icona di visualizzatore d'immagini:

![visualizzatore-d'immagini](https://user-images.githubusercontent.com/2257024/54885418-a5f79480-4e5a-11e9-8594-2630b881e26c.png)

**Comment by Bonandry** [comment]
questi "errori" sono del team di Yaru 
se puoi mi puoi spiegare come lo aggiusti?

**Comment by gusbemacbe** [comment]
Ciao @Bonandry,

> questi "errori" sono del team di Yaru

Esattamente, Sam Hewitt ha fatto molti sbagliati, non se deve utilizzare la maschera che non è compatibile con i file managers e con i docks Docky, Latte Dock e Plank, molto usati dagli utenti di Ubuntu e di GNOME. 

Io vado fare i piccoli tutorial se vuoi. Ma è semplice. Installa il file manager Dolphin:

```
sudo apt-get install dolphin
```

Apri il Dolphin, vai al `~/suru-plus-ubuntu/Suru++-Ubuntu/apps.64` e scopri le icone deformate. Se trovi e vedi un'icona deformata, apri con l'Inkscape. Sull'Inkscape, prima di rimuovere, utilizza il "fill bounded areas"/"colora aree delimitate" (<kbd>Shift</kbd> + <kbd>F7</kbd>):

![esempio](https://user-images.githubusercontent.com/2257024/54900816-601aea80-4eb3-11e9-890a-ea5f1137d051.png)

* Dipinge ognuno oggetto mascherato. Con ciò, puoi rimuovere la maschera degli oggeti. Riaggiusta i nodi degli oggetti dipinti. 
* Il testo deve essere vettorizzato (sull'Inkscape, Path -> Object to Path (in italiano, Tracciato -> da oggetto a tracciato)). 
* I contorni anche devono essere vettorizzati (sull'Inkscape Path -> Stroke to Path (in italiano, Tracciato -> da contorno a tracciato))

Se non capisci, ti posso fare i tutorial-video se vuoi.

**Comment by Bonandry** [comment]
ho capito

**Comment by Bonandry** [comment]
![Schermata da 2019-03-25 08-20-20](https://user-images.githubusercontent.com/7957697/54901489-e5fc5d00-4ed6-11e9-9761-feac52320ba5.png)
dolphin non mi fa vedere le anteprime

**Comment by gusbemacbe** [comment]
@Bonandry 

Hai bisogno di abilitare la anteprima. 

Clicca su Controllo -> Configura Dolphin --> Generale --> Anteprime e selecciona "Immagini SVG"

**Comment by gusbemacbe** [comment]
![image](https://user-images.githubusercontent.com/2257024/54901661-ee906b80-4eb5-11e9-8080-59dffd185971.png)

**Comment by Bonandry** [comment]
![Schermata da 2019-03-25 08-29-23](https://user-images.githubusercontent.com/7957697/54901873-20b2c500-4ed8-11e9-8906-f0c2e1e39b38.png)
non ho quelle opzioni

**Comment by gusbemacbe** [comment]
Apri il terminale, esegui il commando `dolphin --version`, copia e incolla qui.

**Comment by gusbemacbe** [comment]
Chiuse il Dolphin. Installa un plugin de anteprima e di visualizzazione:

```
sudo apt install kdegraphics-thumbnailers
```

**Comment by gusbemacbe** [comment]
Ha funzionato per te?

**Comment by gusbemacbe** [comment]
Ciao @Bonandry, l'icona `fcitx.svg` non è un visualizzatore d'immagini né un editore d'immagini, ma è una tastiera. Vado aggiornare.

**Comment by Bonandry** [comment]
è il computer che uso  e sono tra dolphin e gli extra 300 mb di programma, quando ho tempo cambio HD e lo installo

**Comment by Bonandry** [comment]
ho portato le icone action da 1450 a 930 
supporto per Inkscape, gparted, gtkpod, evolution

**Comment by gusbemacbe** [comment]
Molto bene, @Bonandry ! La dimensione del tema di icone sarà molto ottimizzata.

**Comment by Bonandry** [comment]
ho abbassato il bianco dentro l'icona Firefox

una domanda, dove visualizzo la pagina con il download della versone BETA?

**Comment by gusbemacbe** [comment]
Ciao @Bonandry 

Ecco il mio video (fa un clic sul video per visualizzare plenamente):

![Visualizzare la versione beta](https://user-images.githubusercontent.com/2257024/54917857-818fcc80-4edb-11e9-87a0-a9f1c2cdf294.gif)

**Comment by Bonandry** [comment]
ok grazie

**Comment by Bonandry** [comment]
ho aggiunto action mancanti

**Comment by Bonandry** [comment]
ho portato a 910 le icone in action, alcune icone non cambiano colore, potresti correggerle?

**Comment by gusbemacbe** [comment]
Sì, posso. Ma in un'ora, perché sto prendendo un poco riposo, perché io ho disegnato molto i progetti architettonici della mia sorella durante 7 ore, lei non sa fare niente.

**Comment by gusbemacbe** [comment]
@Bonandry, ho aggiornato i colori di `actions/16`, scusami per la mia assenza, io stavo molto malato perché i progetti architettonici mi hanno causato dolore dagli occhi. Anche ho corretto i collegamenti rotti di `system-log-out.svg`.

**Comment by gusbemacbe** [comment]
![handbrake](https://user-images.githubusercontent.com/2257024/54985214-29b29d80-4f8f-11e9-9dd8-3af2537b050e.png)

**Comment by gusbemacbe** [comment]
![freemind](https://user-images.githubusercontent.com/2257024/54989987-6a62e480-4f98-11e9-8c13-71288f268552.png)

![frostwire](https://user-images.githubusercontent.com/2257024/54989999-70f15c00-4f98-11e9-940e-df278287f38c.png)

**Comment by gusbemacbe** [comment]
![immagini](https://user-images.githubusercontent.com/2257024/54997426-6f309400-4faa-11e9-9aca-136b214f6c0d.png)

**Comment by Bonandry** [comment]
ottimo lavoro

**Comment by Bonandry** [comment]
![Schermata da 2019-03-27 19-26-59](https://user-images.githubusercontent.com/7957697/55102324-6df48980-50c6-11e9-8d9d-0b6e417fbcb6.png)
ho provato a ottimizzare il set ma sembra che ci sia un errore

**Comment by gusbemacbe** [comment]
@Bonandry

Prova

```
cd ~/.icons/Suru++Ubuntu/actions/16/ 
```

Se non, prova nuovamente:

```
cd ~/.icons/Suru++-Ubuntu/actions/16/ 
```

**Comment by gusbemacbe** [comment]
SE non funziona per te, dove hai salvato la cartella "suru-plus-ubuntu"? Su Documenti?

**Comment by Bonandry** [comment]
è su home>.icons

**Comment by Bonandry** [comment]
ok funziona con la seconda

**Comment by gusbemacbe** [comment]
Chieso e la discussione continua sul #60.
