### ISSUE TITLE
Icone aggiunte o modificate

### ISSUE THREAD

**Issue by Bonandry** [Bonandry/suru-plus-ubuntu#60]
aggiunto due app gnome: de.haeckerfelix.Fragments, org.gnome.PasswordSafe
modificato l'icona org.gnome.eog in stile Gnome 3.32
l'icona gnome-hearts 
l'icona org.gnome.Aisleriot, gnome-aisleriot

**Comment by gusbemacbe** [comment]
Stai attento:

* Le icone `eog.svg` e `org.gnome.eog.svg` è collegata all'icona `visualizzatore-di-immagini.svg`;
* Le icone `gnome-hearts.svg`, `org.gnome.Aisleriot.svg` e `gnome-aisleriot` sono collegate all'icona `carde.svg`.

**Comment by gusbemacbe** [comment]
Ciao, non hai bisogno di multiplicare le copie non-collegate di `eog`, perché loro sono già collegate all'icona generica `visualizzatore-di-immagini.svg`. QUando vuoi rifare le icone al stilo di GNOME 3.32, cercale sulla cartella `icone-generiche`. Ho corretto l'icona:

![visualizzatore-d'immagini-alt](https://user-images.githubusercontent.com/2257024/55039200-0bd25080-5002-11e9-8e41-34ef590554d7.png)

**Comment by Bonandry** [comment]
io vorrei che l'icona EOG sia un tipo e l'icona VISUALIZZATORE un altra
stesso discorso per i gama, un icona per Aisleriot e una per Heart

**Comment by gusbemacbe** [comment]
Ok, @Bonandry, Vado fare downgrade per la precedente versione.

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

Ho retrocesso e resettato alla precedente versione, riguardo Eom e Aisleriot, ma riaggiustato le referenze di icone alternative per facilitare il tuo lavoro.

**Comment by gusbemacbe** [comment]
Ciao @Bonandry 

![masterpdfeidtor](https://user-images.githubusercontent.com/2257024/55148003-33bad480-5126-11e9-8d42-1f85fc5d8467.png)

**Comment by gusbemacbe** [comment]
Qual una di quelle icone è corretta?

![imagem](https://user-images.githubusercontent.com/2257024/55148161-7381bc00-5126-11e9-9a53-43ea1073b442.png)

**Comment by Bonandry** [comment]
la seconda è per baobab
la prima è partitionmanager

**Comment by Bonandry** [comment]
nelle icone generiche ho messo una icone "calendar" in stile gnome 3.32, vorrei sapere una tua opinione

**Comment by gusbemacbe** [comment]
La nuova icona di calendario è molto bella di quella allo stile di Yaru. La nuova icona generica di "calendario" può essere collegato a tutte le icone di applicazioni di calendario? È molto bella!

**Comment by Bonandry** [comment]
ok allora utilizziamola, che ne dici di ufficializzare la versione beta?

**Comment by gusbemacbe** [comment]
Ancora non, il tema di icone non sta completamente corretto. Ci sono ancora ne alcune icone deformate. Io credo che deve essere pronto domani od il lunedì.

**Comment by Bonandry** [comment]
ok

**Comment by gusbemacbe** [comment]
![robot](https://user-images.githubusercontent.com/2257024/55289379-8ac9df00-539c-11e9-82a2-74e7eaf1303a.png)

**Comment by Bonandry** [comment]
ho fatto un istallazione pulita di 18.04.2 con il nuono aggiornamento gnome
le icone:
org.gnome.SystemMonitor
org.gnome.Logs
org.gnome.Calculator
org.gnome.Characters
non cambiano con SURU++
anche l'icona pyrenamer va cambiata a mano

**Comment by gusbemacbe** [comment]
Vado vedere le icone.

E eccola:

![cairo-dock](https://user-images.githubusercontent.com/2257024/55289803-a8e60e00-53a1-11e9-8d1a-6dd408f9d40b.png)

**Comment by gusbemacbe** [comment]
Con ou senza il suffisso `-symbolic`?

![image](https://user-images.githubusercontent.com/2257024/55289825-d7fc7f80-53a1-11e9-8032-f1eca0475fe8.png)

**Comment by gusbemacbe** [comment]
L'icona di Totem è molto bella. Può essere collegata a tutte le icone di applicazioni di film/video?

**Comment by gusbemacbe** [comment]
Qual'è una di queste icone è in stile GNOME 3.32? 

Tutte queste icone sono le stesse applicazioni di negozio di applicazioni **con i suoi aggiornamenti**. 

![image](https://user-images.githubusercontent.com/2257024/55290158-eea4d580-53a5-11e9-98bf-142af2b41537.png)

**Comment by Bonandry** [comment]
nessuna

**Comment by Bonandry** [comment]
> L'icona di Totem è molto bella. Può essere collegata a tutte le icone di applicazioni di film/video?
no, solo per totem

**Comment by Bonandry** [comment]
> Con ou senza il suffisso `-symbolic`?
> 
> ![image](https://user-images.githubusercontent.com/2257024/55289825-d7fc7f80-53a1-11e9-8032-f1eca0475fe8.png)
questa icona "applications-system-symbolic" può essere eliminata

**Comment by Bonandry** [comment]
> Qual'è una di queste icone è in stile GNOME 3.32?
> 
> Tutte queste icone sono le stesse applicazioni di negozio di applicazioni **con i suoi aggiornamenti**.
> 
> ![image](https://user-images.githubusercontent.com/2257024/55290158-eea4d580-53a5-11e9-98bf-142af2b41537.png)

ARANCIO - Software centre
BLU - proprietà
DARK - aggiornamento

**Comment by gusbemacbe** [comment]
OK, @Bonandry , vado creare le icone generiche `applicazione.svg` (arancia), `aggiornamento-di-applicazioni.svg` (oscuro) e `proprietà-di-applicazioni.svg` (blu). Vado correggere la deformazione dell'icona blu.

**Comment by gusbemacbe** [comment]
Ciao @Bonandry 

Hai bisogno di fare due icone monocromatiche (16px) differente: `aggiornamento-di-applicazioni.svg` e `proprietà-di-applicazione.svg`.

**Comment by Bonandry** [comment]
fatto, le carico

**Comment by Bonandry** [comment]
le icone per mint si possono eliminare?

**Comment by gusbemacbe** [comment]
Sì, puoi.

Ecco:

![image](https://user-images.githubusercontent.com/2257024/55291540-f7050c80-53b5-11e9-8e9f-f7a1ec0e4a2c.png)

Il `gnome-sound-recorder` è un'applicazione di registrare e scrivere un **podcast**, e non di registrare e scrivere l'audio. 

Ma qual'è l'icona corretta? Ecco l'icona originale di podcast sui gadget di Apple – iPod, iPod nano, iPhone ed iPad da 2005:

https://itunes.apple.com/us/app/apple-podcasts/id525463029

**Comment by gusbemacbe** [comment]
Ho rimosso le icone di Linux Mint.

**Comment by Bonandry** [comment]
direi di utilizzare l'icona podcast-app

**Comment by Bonandry** [comment]
ho inserito una nuova icona per qbitorrent

**Comment by gusbemacbe** [comment]
L'icona di sudoku sta sbagliata:

<img src="https://raw.githubusercontent.com/Bonandry/suru-plus-ubuntu/beta/Suru%2B%2B-Ubuntu/apps/scalable/gnome-sudoku.svg?sanitize=true" alt="sudoku" height="120px"/>

L'icona corretta del mio Suru++ 25 è:

<img src="https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/Suru%2B%2B/apps/64/ksudoku.svg?sanitize=true" alt="sudoku" height="120px"/>

Vedi le immagini sul DuckDuckGo:
https://duckduckgo.com/?q=sudoku&t=ffab&atb=v1-1&iax=images&ia=images

**Comment by Bonandry** [comment]
quella è l'icona nel set yaru

ho migliorato le icone bitorrent e utorrent

**Comment by gusbemacbe** [comment]
AH, loro hanno fatto un sbagliato. Io vado discutere con loro.

**Comment by Bonandry** [comment]
la tua icona è molto buona, ho caricato un altra versione

**Comment by gusbemacbe** [comment]
Di quale le icone?

**Comment by Bonandry** [comment]
sudoku

**Comment by gusbemacbe** [comment]
Migliore adesso!

**Comment by Bonandry** [comment]
ok

**Comment by gusbemacbe** [comment]
Anche hai bisogno di cambiare l'icona monocromatica (16px) di sudoku, perché gli utenti vanno pensare che è un gioco di tris.

**Comment by Bonandry** [comment]
ok

**Comment by Bonandry** [comment]
fatto

**Comment by gusbemacbe** [comment]
@Bonandry,

Io ho pubblicato l'issue sul repositorio Yaru e gli sviluppatori e grafici di Suru e Yaru hanno riconosciuto lo sbagliato nell'icona di sudoku. :-) 

Vedi l'immagini, tutte queste applicazioni sono applicazioni di monitor di sistema. Osserva che le icone azzurre turchese non sono leggibili, gli utente possono non capire l'icona, perciò, hai bisogno di migliorare i colori. Qual'è l'icona corretta?

![image](https://user-images.githubusercontent.com/2257024/55292979-4a338b00-53c7-11e9-9a30-e16b6291b957.png)

**Comment by Bonandry** [comment]
utilizziamo org.gnome.SystemMonitor

**Comment by gusbemacbe** [comment]
Qual'è l'icona corretta?

![image](https://user-images.githubusercontent.com/2257024/55293707-b2866a80-53cf-11e9-8eed-6da92ba4baf5.png)

**Comment by Bonandry** [comment]
la bianca

**Comment by Bonandry** [comment]
corretta

**Comment by gusbemacbe** [comment]
Qual'è l'icona corretta?

![image](https://user-images.githubusercontent.com/2257024/55295295-c76bf980-53e1-11e9-9e7b-88eb0a4c57f7.png)

**Comment by gusbemacbe** [comment]
![weather](https://user-images.githubusercontent.com/2257024/55296476-6bf53800-53f0-11e9-9b4d-360bdf044700.png)

**Comment by gusbemacbe** [comment]
Tutte queste applicazioni sono applicazioni di stazione radio. Ecco l'icona del mio Suru++:

<img src="https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/Suru%2B%2B/apps/64/radiotray.svg?sanitize=true" alt="radio" height="120px"/>

E ecco le tue icone differenti, e cosa pensi dell'icona gialla? Vedi:

![image](https://user-images.githubusercontent.com/2257024/55296917-63076500-53f6-11e9-9014-ee0d2c9a5ec0.png)

**Comment by gusbemacbe** [comment]
Per favore, legge l'immagine:

![suggerimento](https://user-images.githubusercontent.com/2257024/55302032-c5239280-5415-11e9-8070-2edfb45e3246.png)

**Comment by gusbemacbe** [comment]
![google](https://user-images.githubusercontent.com/2257024/55303860-ff456200-541e-11e9-9a5e-9b3a99e90d54.png)

**Comment by Bonandry** [comment]
> Tutte queste applicazioni sono applicazioni di stazione radio. Ecco l'icona del mio Suru++:
> 
> <img alt="radio" height="120px" src="https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/Suru%2B%2B/apps/64/radiotray.svg?sanitize=true">
> 
> E ecco le tue icone differenti, e cosa pensi dell'icona gialla? Vedi:
> 
> ![image](https://user-images.githubusercontent.com/2257024/55296917-63076500-53f6-11e9-9014-ee0d2c9a5ec0.png)

de.haeckerfelix.Radio

**Comment by Bonandry** [comment]
> Per favore, legge l'immagine:
> 
> ![suggerimento](https://user-images.githubusercontent.com/2257024/55302032-c5239280-5415-11e9-8070-2edfb45e3246.png)

per il cifrario usiamo quella stile gnome 3.32
per la crittografia l'icona stile pass come in gnome 3.32
per il backup anche gnome 3.32 usa l'immagine caveau, se vuoi posso modificarla in stile gnome 3.32
ora la faccio e la inserisco nelle Generiche poi tu decidi la più bella

**Comment by Bonandry** [comment]
> Qual'è l'icona corretta?
> 
> ![image](https://user-images.githubusercontent.com/2257024/55295295-c76bf980-53e1-11e9-9e7b-88eb0a4c57f7.png)

per i Tweaks usiamo org.gnome.tweaks
per la Configurazione ho caricato la nuova icona nelle Generiche

**Comment by gusbemacbe** [comment]
La nuova icona di backup è molto bella, ma non ha un senso che backup sia un caveau. Ti mostro le icone di Time Machine, un'applicazione di backup, del macOS d'Apple, vedi [le immagini qui](https://duckduckgo.com/?q=time+machine+icon&t=ffab&atb=v1-1&iax=images&ia=images).

Perciò, io ho creato le due icone alternative simili all'icona di Time Machine, ho scelto l'arancio e la melanzana di paletta di colori di Canonical/Ubuntu e mi piacerebbe proporlete:

<img src="https://raw.githubusercontent.com/Bonandry/suru-plus-ubuntu/5a8ead5ff001a2b539664c9ff31317fe5975a6ee/icone-generiche/backup.svg?sanitize=true" alt="backup 1" height="150px"> <img src="https://raw.githubusercontent.com/Bonandry/suru-plus-ubuntu/5a8ead5ff001a2b539664c9ff31317fe5975a6ee/icone-generiche/backup-alt2.svg?sanitize=true" alt="backup 2" height="150px">

**Comment by gusbemacbe** [comment]
Quale "questa"? Quella che hai creato?

**Comment by Bonandry** [comment]
o quella che ho messo in generuche, ma io penso che quella gnome style rimanga la preferita

**Comment by Bonandry** [comment]
ok, ti avevo segnalato:
ho fatto un istallazione pulita di 18.04.2 con il nuovo aggiornamento gnome
le icone:
org.gnome.SystemMonitor
org.gnome.Logs
org.gnome.Calculator
org.gnome.Characters
non cambiano con SURU++
anche l'icona pyrenamer va cambiata a mano

**Comment by gusbemacbe** [comment]
@Bonandry !

Come ti ho detto che il tuo tema di icone è licenziato sotto GPL3, gli utenti posso fare cosa loro vogliono con il tuo tema, come avere totale libertà di cambiare le icone alternative se lo stile GNOME 3.32 ou altri colori di certe icone non gli piacciono, perciò, ho creato la cartella `alternatives`. Visita [CHANGELOG](https://github.com/Bonandry/suru-plus-ubuntu/blob/beta/CHANGELOG.md), clicca sull'Italiano. 

Adesso non possiamo ufficializzare la versione beta perché ci sono poche icone deformate che hanno bisogno di essere corrette e migliorate. Come non puoi vederle su Dolphin in tuo computer per correggerle, io lo faccio da solo.

**Comment by Bonandry** [comment]
ho sostituito l'icona Deja-dup come vorrei di default
ho corretto una imperfezione nell'icona caveau
ho sostituito l'icona "cronologia" con una in Gnome 3.32 style
ho inserito nelle Generiche l'icone che non cambiano

**Comment by gusbemacbe** [comment]
![gsconnect](https://user-images.githubusercontent.com/2257024/55420282-05d1f780-554d-11e9-99f3-9aac7ff08e8e.png)

**Comment by gusbemacbe** [comment]
![translator](https://user-images.githubusercontent.com/2257024/55424409-96f99c00-5556-11e9-9e16-976986f9bb23.png)

**Comment by Bonandry** [comment]
sono tutti problemi che arrivano da Sam

**Comment by gusbemacbe** [comment]
Sam non capisce che la maschera e l'oggetto sfocato non sono compatibili con certi file manager (Dolphin, Polo, Krunner, ecc.) e con i certi dock (Docky, Latte Dock, Plank, ecc.).

**Comment by Bonandry** [comment]
ho fatto le icone shermata e orologio in stile gnome 3.32 e ho cambiato l'icona search

**Comment by gusbemacbe** [comment]
Perfette le icone!

**Comment by gusbemacbe** [comment]
Io me sono accorto che le cartelle di `apps` avevano il differente numero di icone perché hai dimenticato di aggiungerle. Ho copiato le icone perdute dalla `16` per la `scalable`, le ho riaggiustate e ho copiato le icone perdute dalla `scalable` per le `16` e `symbolic` e le ho riaggiustate.

**Comment by gusbemacbe** [comment]
Per favore, vedi la descrizione completa del commit 769572601076e8dce9c4fae361536159c3d112a0 qui. (fa un clic su questi numeri)

**Comment by gusbemacbe** [comment]
Per favore, vedi le icone monocromatiche sulla cartella `icone-generiche` e falle come `scalable`. 

E qual'è l'icona corretta? Vedi l'icona di video al stile GNOME 3.32.

![image](https://user-images.githubusercontent.com/2257024/55446300-6e44c700-5595-11e9-9ef8-28685d72f9f0.png)

**Comment by gusbemacbe** [comment]
![hotspot](https://user-images.githubusercontent.com/2257024/55447794-8f101b00-559b-11e9-8769-9394b066a557.png)

**Comment by gusbemacbe** [comment]
Qual'è l'icona corretta di Inkscape? 

![inskcape-icons](https://user-images.githubusercontent.com/2257024/55447822-be268c80-559b-11e9-9c2d-3b9780ae77db.png)

**Comment by Bonandry** [comment]
> Per favore, vedi le icone monocromatiche sulla cartella `icone-generiche` e falle come `scalable`.
> 
> E qual'è l'icona corretta? Vedi l'icona di video al stile GNOME 3.32.
> 
> ![image](https://user-images.githubusercontent.com/2257024/55446300-6e44c700-5595-11e9-9ef8-28685d72f9f0.png)
ogni icona deve essere differente in base al programma, nei prossimi giorni le farò in stile originale del software

**Comment by Bonandry** [comment]
> Qual'è l'icona corretta di Inkscape?
> 
> ![inskcape-icons](https://user-images.githubusercontent.com/2257024/55447822-be268c80-559b-11e9-9c2d-3b9780ae77db.png)
quella su sfondo chiaro

**Comment by Bonandry** [comment]
> Per favore, vedi la descrizione completa del commit [7695726](https://github.com/Bonandry/suru-plus-ubuntu/commit/769572601076e8dce9c4fae361536159c3d112a0) qui. (fa un clic su questi numeri)
le tre icone di xfburn non necessitano "scalable" perche sono icone di programma, forse è meglio inserirle nella cartella ACTION

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

> Calligrastage e Stage non sono per i video? sono programmi per KDE?

Calligra Stage è un programma di presentazione (come Microsoft PowerPoint). Sì, sono programmi di KDE ma non ufficiali di un ambiente KDE, perché è parte della **suite office** Calligra (Flow, Gemini, Karbon, Kexi, Krita, Sheets, Tables, Words anche ne fanno parte), in stessa forma che Microsoft Word è parte della **suite office** Microsoft Office. Poi gli utenti di Ubuntu **e di Ubuntu Touch o Android** possono installare la suite office Calligra senza dipendere di KDE. Como io sono un utente di Ubuntu, preferisco le applicazioni di questa suite office a quelle della LibreOffice. 

Puoi leggere l'articolo in italiano: https://it.wikipedia.org/wiki/Calligra_Suite

Mi piace molto la nuova icona di Mine, è più bella di l'antica icona al stile di Yaru. 

Credo che hai bisogno di migliorare l'icona, perché quest'applicazione non è un'applicazione di un'anteprima di font, ma di un'anteprima di icone:

![image](https://user-images.githubusercontent.com/2257024/55482900-dded9d00-55fb-11e9-825e-96c68f310098.png)

**Comment by Bonandry** [comment]
io direi di eliminare Calligra Stage

modifico l'icona

**Comment by gusbemacbe** [comment]
@Bonandry 

L'icona di `karts` non deve essere un'icona di gioco, ma deve essere un'icona di vettura monoposto a ruote scoperte. 

![image](https://user-images.githubusercontent.com/2257024/55521994-841bc000-5659-11e9-9f07-661e7e3a20a2.png)

**Comment by gusbemacbe** [comment]
Ho rimosso le icone di applicazioni della suite office Calligra KDE.

Kopete e Krita sono applicazioni di KDE, e Krita è parte della suite office Caligra KDE, vuoi eliminarle o mantenerle?

**Comment by Bonandry** [comment]
> Ho rimosso le icone di applicazioni della suite office Calligra KDE.
> 
> Kopete e Krita sono applicazioni di KDE, e Krita è parte della suite office Caligra KDE, vuoi eliminarle o mantenerle?

si mantengono, conosco molte persone che le usano

**Comment by Bonandry** [comment]
le icone monocromatiche sono tutte un po generiche, se è un gioco ho messo il pad, rifarle tutte sarebbe un grande lavoro

**Comment by Bonandry** [comment]
delete icon Pithos pithos
change icon sonata cantata
added icon io.github.Pithos pithos-tray-icon

**Comment by gusbemacbe** [comment]
Mi piacciono molto le nuove icone. Congrats!

Ma non hai bisogno di rimuovere le icone collegate, perché quando tu aggiorni l'icona originale, le icone collegate sono automaticamente aggiornate, poi non hai bisogno di fare multiple copie dell'icona. Ricordati che il collegamento aiuta a ridurre la dimensione del tema di icone. Grazie al collegamento, la dimensione del tema di icone è ridotta di 170MB per 30MB.

**Comment by Bonandry** [comment]
ok, ma alcune icone devono rimanere nella vecchia versione
ho modificato l'icona livewallpaper e ho aggiunto livewallpaper-config e il suo indicatore in status

**Comment by Bonandry** [comment]
sto facendo i collegamenti

**Comment by Bonandry** [comment]
ho fatto alcuni collegamenti, controlla che siano fatti bene 
esempio
ln -sfnr file-manager.svg Thunar.svg
si possono fare tutte con un solo coimando?

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

Sì, puoi, ma muovi le icone simili per l'altra cartella, per evitare che tutte le 2 mille icone siano collegate a un'icona originale. Sull'altra cartella con le icone mosse, fa tutte con un solo commando:

```
echo "Nuovo collegamento"; read nuovo; for vecchio in *.svg; do; ln -sfnr $nuovo $vecchio; done
```

**Comment by gusbemacbe** [comment]
E hai bisogno di migliorare le icone di LiveWallpaper, perché hai utilizzato la maschera:

![livewallpaper](https://user-images.githubusercontent.com/2257024/55572799-d3f09a80-56de-11e9-8d44-f2d374e3f2ad.png)

1. Rimouve la maschera.
2. Dupplica l'oggetto bianco.
3. Crea il gradiente sull'oggetto bianco.
4. Muove un poco l'oggetto del gradiente alla sinistra e sotto.
5. Pronto!

**Comment by gusbemacbe** [comment]
Hai dimenticato di aggiungere le icone `livewallpaper-config` e `sonata` per le cartelle `16` e `symbolic`.

**Comment by Bonandry** [comment]
fatte, controlla il livewallpaper

**Comment by gusbemacbe** [comment]
Solo una suggestione. 

Credo che Caja, Dolphin, Nautilus, Nemo, PCMFM Polo e Thunar devono essere differenti, perché gli utente possono se sentire confusi con le stesse icone di differenti file managers. Nel mio caso, io utilizzo Dolphin, Nautilus, PCMFM e Thunar. 

Per esempio delle icone del mio Suru++ 25:


* Dolphin (perché é un delfino nell'onda):

<img src="https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/Suru%2B%2B/apps/64/dolphin.svg?sanitize=true" alt="backup official" height="64px">

* Nautilis (Nautilus è uguale al Finder):

<img src="https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/Suru%2B%2B/apps/64/nautilus.svg?sanitize=true" alt="backup official" height="64px">

* Nemo (perché era sviluppato dagli sviluppatori di Linux MInt, perciò, Nemo è verde):

<img src="https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/Suru%2B%2B/apps/64/nemo.svg?sanitize=true" alt="backup official" height="64px">

* Polo (il suo proprio logotipo):

<img src="https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/Suru%2B%2B/apps/64/polo.svg?sanitize=true" alt="backup official" height="64px">

* Thunar (è un simbolo viking, a causa del Thor ed il suo martello (il martello era ufficializzato dagli sviluppatori di Thunar):

<img src="https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/Suru%2B%2B/apps/64/thunar.svg?sanitize=true" alt="backup official" height="64px">

**Comment by gusbemacbe** [comment]
Congrats, @Bonandry ! Sai come correggere il bug della maschera!

![image](https://user-images.githubusercontent.com/2257024/55574279-69415e00-56e2-11e9-8227-67cd90b73a6b.png)

**Comment by Bonandry** [comment]
ok  però Nautilus deve rimanere come è ora, gli altri se ce li hai già fatti caricali te

**Comment by gusbemacbe** [comment]
Come le cartelle di `apps` hanno numeri differenti di icone, io ho utilizzato Meld per trovare le icone perdute. Hai dimenticato di aggiungere le icone `menu.svg` e `volume.svg` per `16` e `symbolic`

**Comment by gusbemacbe** [comment]
> ok però Nautilus deve rimanere come è ora, gli altri se ce li hai già fatti caricali te

OK, farò.

**Comment by Bonandry** [comment]
vero!! lo faccio

**Comment by Bonandry** [comment]
OK fatto

**Comment by Bonandry** [comment]
ho fatto tutti i collegamenti in scalable ma mi da un errore di conflitto 
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

**Comment by gusbemacbe** [comment]
Nel terminale:

```
git push
# non ti preoccupare con gli errori... Continua...
git pull
git push
```

**Comment by Bonandry** [comment]
non succede niente

**Comment by Bonandry** [comment]
dove lo apro il terminale dentro la cartella principale?

**Comment by Bonandry** [comment]
git push
fatal: not a git repository (or any of the parent directories): .git

**Comment by gusbemacbe** [comment]
Per aprire la cartella principalle, dal Nautilus, con il terminale, hai bisogno di installare:

```
sudo apt-get install nautilus-open-terminal
killall nautilus && nautilus &
```

Apri il Nautilus e vai alla cartella dove sta la cartella principale. Clica sulla cartella principale con il pulsante destro del mouse e seleziona "Apri in terminale". 

E esegui i commandi:

```
git config --global core.editor "gedit --wait"
git add .
git commit -m "Fixed pull and push"
git push
# Ci saranno errori, ma non ti preoccupare, continua
git pull
git push
```

**Comment by Bonandry** [comment]
ok ora funziona, controlla che tutto sia ok

**Comment by gusbemacbe** [comment]
Congrats, sei più rapido di me e quasi hai finito il lavoro, ma ci sono qualcosa che ha bisogno di essere migliorato. Io ho bisogno di lavorare con poche icone deformate che ancora non sono migliorate. 

L'icona `mpv.svg` sulla cartella `16` non è un'applicazione di musica, ma quella di video.

**Comment by gusbemacbe** [comment]
![nuovaplayer](https://user-images.githubusercontent.com/2257024/55590600-b684f600-5709-11e9-8e28-0d4dadbf9e4a.png)

![okleta](https://user-images.githubusercontent.com/2257024/55590609-bf75c780-5709-11e9-9cbd-e212d78011e2.png)

**Comment by gusbemacbe** [comment]
![ephiphany](https://user-images.githubusercontent.com/2257024/55591101-0c0dd280-570b-11e9-8dc4-fddf9b704686.png)

**Comment by gusbemacbe** [comment]
![qbrowser](https://user-images.githubusercontent.com/2257024/55598270-3fab2580-5728-11e9-9858-cbbcb5646744.png)

**Comment by gusbemacbe** [comment]
![rstudio](https://user-images.githubusercontent.com/2257024/55598868-5141fc80-572b-11e9-82f6-8bed5c3e56c2.png)

**Comment by Bonandry** [comment]
> L'icona `mpv.svg` sulla cartella `16` non è un'applicazione di musica, ma quella di video.

Fatto
