### ISSUE TITLE
Cosa resta da fare

### ISSUE THREAD

**Issue by Bonandry** [Bonandry/suru-plus-ubuntu#64]
i collegamenti alla scalable sono fatti
i numeri delle icone sono tutti uguale
facciamo un elenco di modifiche rimaste da fare

**Comment by gusbemacbe** [comment]
> facciamo un elenco di modifiche rimaste da fare

Quale?

**Comment by Bonandry** [comment]
cosa rimande da fare prima del rilascio?

**Comment by gusbemacbe** [comment]
1. Prima abbiamo bisogno di correggere alcune icone deformate: SeaMonkey, Skype, Stellarium, TeX Doc, Vivaldi e Wikipedia;

2. Hai bisogno di migliorare l'icona di BleachBit, perché gli utenti pensano che BleachBit è un'applicazione di passwords o per hacker. Ecco l'esempio dell'icona di BleachBit del mio Suru++ 25:

<img src="https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/Suru%2B%2B/apps/64/bleachbit.svg?sanitize=true" alt="BleachBit" height="124px"/>

3. Come gli utenti hanno lamentato che il tuo tema di icone è molto limitato e tu non gli offristi le opzioni fi colore delle cartelle. Ho bisogno di creare poche colori delle cartelle con l'aiuto di @SmartFinn. 

4. Finalmente, devo fare colori alternative della icona di macchina calcolatrice.

5. Prima del rilascio, ho bisogno di fare presentazioni sull'OpenDesktop, per esplicare cosa è nuovo in questa nuova versione del tema di icone. 

6. Pronto.

**Comment by Bonandry** [comment]
Prima abbiamo bisogno di correggere alcune icone deformate: SeaMonkey, Skype, Stellarium, TeX Doc, Vivaldi e Wikipedia;

spero di aver risolto

**Comment by Bonandry** [comment]
nuova icona per bleachbit

**Comment by gusbemacbe** [comment]
Scusami per la mia assenza! Io stava nella banca.

Congrats, @Bonandry! Hai risolto i bug delle icone! Ma Skype ancora è strana. 

![image](https://user-images.githubusercontent.com/2257024/55642476-edf5b000-57a6-11e9-8c6c-e757978eb547.png)

Comparando all'icona del mio Suru++ 25:

<img src="https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/Suru%2B%2B/apps/64/skype.svg?sanitize=true" alt="Skype" height="124px"/>

Qual'è l'icona corretta?

![image](https://user-images.githubusercontent.com/2257024/55642555-2bf2d400-57a7-11e9-9b6b-5d9257647313.png)

**Comment by gusbemacbe** [comment]
Mi piace molto la nuova icona "bloc-notes"!

**Comment by Bonandry** [comment]
> Scusami per la mia assenza! Io stava nella banca.
> 
> Congrats, @Bonandry! Hai risolto i bug delle icone! Ma Skype ancora è strana.
> 
> ![image](https://user-images.githubusercontent.com/2257024/55642476-edf5b000-57a6-11e9-8c6c-e757978eb547.png)
> 
> Comparando all'icona del mio Suru++ 25:
> 
> <img alt="Skype" height="124px" src="https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/Suru%2B%2B/apps/64/skype.svg?sanitize=true">
> 
> Qual'è l'icona corretta?
> 
> ![image](https://user-images.githubusercontent.com/2257024/55642555-2bf2d400-57a7-11e9-9b6b-5d9257647313.png)

l'icona skype è con il simbolo centrale e il contorno intorno 
ho sistemato l'icona notifications

**Comment by Bonandry** [comment]
tra poche ore andrò via e tornerò tra 3 giorni!

**Comment by gusbemacbe** [comment]
Ottimo lavoro! Mi piace molto le nuove icone al stile GNOME 3.32, come rubrica. Migliori di antiche icone al stile di Yaru!

> tra poche ore andrò via e tornerò tra 3 giorni!

Viaggerai? In tua assenza, mi prenderò cura del tuo tema di icone, OK?

**Comment by Bonandry** [comment]
si un piccolo viaggio!! da Firenze a Roma

**Comment by gusbemacbe** [comment]
Credo che hai bisogno di migliorare poche icone:

* `android.svg` – Google vieta allo sviluppatore di modificare l'androide, hiede allo sviluppatore di mantenere l'icona originale di Android
* `gcr-smart-card.svg` –  molto realistico al stile di GNOME 3.32 o di Yaru. 
* `playonlinux.svg` – comparando all'icona del mio Suru++ 25:
<img alt="Skype" height="124px" src="https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/Suru%2B%2B/apps/64/playonlinux.svg?sanitize=true">

*  `playstore.svg` – molto realistico al stile di GNOME 3.32, e comparando all'icona del mio Suru++ 25:
<img alt="Skype" height="124px" src="https://raw.githubusercontent.com/gusbemacbe/suru-plus/master/Suru%2B%2B/apps/64/playstore.svg?sanitize=true">

Ci sono solamente tre icone deformate:

![image](https://user-images.githubusercontent.com/2257024/55644820-6495ac00-57ad-11e9-956f-6ee86b3653bf.png)
![image](https://user-images.githubusercontent.com/2257024/55644844-6f504100-57ad-11e9-89a9-be9b9794d654.png)
![image](https://user-images.githubusercontent.com/2257024/55644882-8727c500-57ad-11e9-850f-868876dae5c0.png)

**Comment by Bonandry** [comment]
playonlinux.svg e playstore.svg possiamo usare le tua
le atre tre cerco di sistemarle

non ho capito che devo fare con android

**Comment by Bonandry** [comment]
gcr-smart-card.svg – molto realistico al stile di GNOME 3.32 o di Yaru
l'ho fatto io in stile hicolor

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

Ecco l'icona originale offerta da Google:
https://developer.android.com/images/brand/Android_Robot.svg

Google ti chiede di utilizzare il colore `#78C257`.

**Comment by Bonandry** [comment]
ok fatto

**Comment by gusbemacbe** [comment]
L'icona di Android Studio sta ancora deformata:

![image](https://user-images.githubusercontent.com/2257024/55647348-d3760380-57b3-11e9-85e3-19f694f188f6.png)

**Comment by Bonandry** [comment]
controlla ora

**Comment by gusbemacbe** [comment]
Ancora non risolto. Ma io vado risolverlo, OK?

Ho fatto l'icona `gcr-smart-card` sulla cartella `icone-generiche`, ti piace o non:

<img alt="Smart Card" height="512px" src="https://raw.githubusercontent.com/Bonandry/suru-plus-ubuntu/beta/icone-generiche/gcr-smart-card.svg?sanitize=true">

**Comment by Bonandry** [comment]
bellissima

**Comment by gusbemacbe** [comment]
La vuoi per sostituire la vecchia icona di `gcr-smart-card.svg`?

**Comment by Bonandry** [comment]
certo (y)

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

Come abbiamo aggiunto i nuovi colori delle cartelle, gli utenti di Ubuntu non lamenteranno. ;-) 

1. Ti piacciono i nuovi colori delle cartelle? Tutti i colori sono colori di Suru, GNOME 3.32 e Yaru. I colori di Aubergine e Canconical sono colori di Ubuntu e della società Canonical, che sviluppa l'Ubuntu. 
2. Ti piace il nuovo README e le sue traduzioni sui file README.en e README.it_IT?
3. Ti piace il nuovo wiki? 

Como abbiamo finito il nostro lavoro, possiamo rilasciare, ma vado mettere un poco sul file Registri delle Modifiche e fare presentazioni sull'OpenDesktop oggi.

**Comment by gusbemacbe** [comment]
Il lavoro sta finito e pronto. Vado fare presentazioni sull'OpenDesktop, OK?

**Comment by Bonandry** [comment]
Ok bellissimo lavoro !!!

**Comment by Bonandry** [comment]
le icone in stile gnome 3.32 ci sono anche:
darktable
documenti
monitor-di-sistema
PDF
radio
schermata
selettore-di-colori

**Comment by Bonandry** [comment]
ho modificato, in cartella generica, l'icona calculator, molto più simile a gnome 3.32

**Comment by gusbemacbe** [comment]
Ciao @Bonandry !

Scusami per la mia assenza, la mia sorella stava malata e mi ha richiesto di disegnare oggi il suo lavoro del piano architettonico che prendeva più di 10 ore perche lei va consegnarlo oggi. Lei debbia avermi notificato che lei aveva compiti a casa, poi io potrei avere già disegnato più presto la fine do settimana. 

Tutte queste icone al stile di GNOME 3.32 sono migliori di quelle vecchie. 

> l'icona geary non sono molto sicuro, vorrei un tuo giudizio

Lei è leggibile. Vado aggiornare i registri delle modifiche e i file README prima di fare le presentazioni e rilasciare.

**Comment by Bonandry** [comment]
Bene 👌

**Comment by gusbemacbe** [comment]
La mia sorella noiosa e pigra mi ha nuovamente richiesto di fare suo altro lavoro, ma ho appena finito il lavoro del tuo repositorio. Vado fare presentazioni sull'OpenDesktop.

**Comment by gusbemacbe** [comment]
@Bonandry 

Pronto e rilasciato. Quando vuoi aggiungere, aggiornare e migliore, invia sempre solamente per la _branch_/versione `beta`. La _branch_/versione `master` è solamente per il rilascio settimanale o mensile.
