### ISSUE TITLE
Stupendo

### ISSUE THREAD

**Issue by Bonandry** [Bonandry/suru-plus-ubuntu#71]
Grazie Gustavo, bellissimo lavoro 
una domanda:
cosa significa 
"SURU++ Ubuntu ha vinto e la wiki e la traduzione in italiano"

**Comment by Bonandry** [comment]
non riesco a capire quello che vuoi dire
forse 
Suru++ Ubuntu ha ricevuto in regalo: la wiki e la traduzione in italiano (README, CHANGELOG e wiki in italiano)

**Comment by Bonandry** [comment]
SCRIVI:
Suru++ Ubuntu ha ricevuto in regalo: la wiki e la traduzione in italiano (README, CHANGELOG e wiki in italiano)

**Comment by gusbemacbe** [comment]
Pronto

**Comment by Bonandry** [comment]
una domanda

Utilizza gli script per installare la versione più recente direttamente da questo repository (indipendentemente dalla tua distribuzione):

NOTA: Utilizza lo stesso comando per aggiornare il tema di icone.
Cartella ROOT (raccomandato)
111


io non capisco come devo fare e penso che anche altri utenti hanno il mio problema
-ho aperto il terminale e ho dato quel comando ma mi ha dato un errore, 

[sudo] password di andrea: 
=> Installando 'Suru++-Ubuntu' ...
cp: impossibile eseguire stat di '/tmp/tmp.n5E3B0vj7U/suru-plus-ubuntu-beta/AUTHORS': File o directory non esistente
cp: impossibile eseguire stat di '/tmp/tmp.n5E3B0vj7U/suru-plus-ubuntu-beta/LICENSE': File o directory non esistente
gtk-update-icon-cache: The generated cache was invalid.
=> Pulendo la cache ...
=> Fatto!
andrea@andrea:~$

**Comment by gusbemacbe** [comment]
AH, vado vedere se i file AUTHORS e LICENSE stano presenti.

**Comment by Bonandry** [comment]
ok

**Comment by gusbemacbe** [comment]
AUTHORS e LICENSE stavanno dentro la cartella "Suru++-Ubuntu". Ho transferito fuori che lo script vai copiare questi file per dentro la cartella Suru++Ubuntu. Anche ho visto que stavi installando la branch `beta`. Ho corretto lo script, sostituindo la branch `beta` per la versione `master`. Ho incorporato nella branch `master`. Scusami per la mia mancanza di attenzione!

**Comment by Bonandry** [comment]
[sudo] password di andrea: 
=> Installando 'Suru++-Ubuntu' ...
gtk-update-icon-cache: The generated cache was invalid.
=> Pulendo la cache ...
=> Fatto!
andrea@andrea:~$ 

anche ora non so se funziona

**Comment by gusbemacbe** [comment]
Ha già funzionata per te. 

> gtk-update-icon-cache: The generated cache was invalid.

Non ti preoccupare con questo errore. Questo errore è normale.

Ma vado chiedere al @SmartFinn, OK?

**Comment by gusbemacbe** [comment]
Hi @SmartFinn!

Travis CI has analysed and checked and there was no error. But the terminal told "The generated cache was invalid". Maybe `Makefile` has silenced this error. Please, can you investigate it?

**Comment by SmartFinn** [comment]
@gusbemacbe the bug inside the apps directory:

```sh
$ > sudo gtk-update-icon-cache -f .
gtk-update-icon-cache: The generated cache was invalid.
$ > sudo rm -rf apps/
$ > sudo gtk-update-icon-cache -f .
gtk-update-icon-cache: Cache file created successfully.
$ >
```

**Comment by gusbemacbe** [comment]
@SmartFinn , I searched "icon-cache" in this folder, but I did not find.

**Comment by gusbemacbe** [comment]
@SmartFinn , maybe referring to `proprietà-di-sistema.svg`? Because I remember you told FreeDesktop icons plugin does not accept accented icons names, right?

**Comment by SmartFinn** [comment]
@gusbemacbe yes, that filename is invalid.

**Comment by gusbemacbe** [comment]
Thank you, I will correct.

**Comment by Bonandry** [comment]
Thank you @SmartFinn

**Comment by gusbemacbe** [comment]
@Bonandry, ho appena corretto perché FreeDesktop, che sviluppa il generatore di icon cache, non accetta i nomi accentuati (per esempio, à, è, ì, ò e ù).

**Comment by gusbemacbe** [comment]
@Bonandry 

Testa sul terminale, utilizzando la branch `beta`, per vede se ci non è nessun errore:

```
wget -qO- https://raw.githubusercontent.com/Bonandry/suru-plus-ubuntu/master/install.sh |TAG=beta  sh
```

**Comment by Bonandry** [comment]
perfetto, nessun errore (y)

**Comment by SmartFinn** [comment]
@Bonandry @gusbemacbe I fixed the test https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/commit/d46855ed8757ac2c657958e8319c3e5d1ea80ff5 Please change it in your Makefiles.

```sh
$ > make -k test
# >>> Searching for icons with embedded objects
# >>> Searching for broken symlinks
# >>> Searching for invalid filenames
./Suru++-Ubuntu/apps/16/propriet??-di-applicazione.svg
./Suru++-Ubuntu/apps/scalable/propriet??-di-applicazione.svg
./Suru++-Ubuntu/apps/symbolic/propriet??-di-applicazione-symbolic.svg
Makefile:56: recipe for target 'test_filenames' failed
make: *** [test_filenames] Error 1
make: Target 'test' not remade because of errors.
$ >  
```

**Comment by gusbemacbe** [comment]
Hello @SmartFinn !

Ready and updated. I am going to test on Travis.

I have a doubt: Can I translate the comments of Makefile into Italian to help Andrea to understand what it is happening?

**Comment by SmartFinn** [comment]
@gusbemacbe 

> Can I translate the comments of Makefile into Italian to help Andrea to understand what it is happening?

Sure.
